name: Terraform Plan + Conftest validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform repo
        uses: actions/checkout@v3

      - name: Checkout OPA policies repo
        uses: actions/checkout@v3
        with:
          repository: rrodriguez942/opa-policies-central
          path: opa-policies

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          export_environment_variables: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform init and plan
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > plan.json

      - name: Install conftest
        run: |
          wget -O - https://github.com/open-policy-agent/conftest/releases/download/v0.62.0/conftest_0.62.0_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin/
          conftest --version #test

      - name: Run conftest test
        run: |
          conftest test plan.json --policy opa-policies/terraform --namespace terraform